# Brief words on Markdown
## What is it for? 
### Isn't it useful? 
Used to write down text instead of code (used to specify instructions and information about codes). Support HTML, Latex, and all sort of stuffs, including titles, headings. For instance: 
* One dog
* Two dogs
* Three Corgies

**So two stars give bolded text**
*So one star is Italic*

Equations are also possible, same way as we use in **Latex** : $\beta+\infty^\alpha*x_{-\beta} = 20^3$


In [217]:
#BEFORE YOU START, ALWAYS: Check the path of which Python you are using to install packages
import sys
print(sys.executable)  

C:\Users\HuyenNguyen\Anaconda3\python.exe


### File handling

Python has the (os) module that provides us with many useful methods to work with directories (and files as well).


In [112]:
import os  #import os module

In [216]:
#Locate the present working directory 
os.getcwd()
print(os.getcwd())
#The extra backslash implies an escape sequence. The print() function will render this properly.

C:\Users\HuyenNguyen\Dropbox (Erasmus Universiteit Rotterdam)\Hamburg


In [215]:
#Change working directory
os.chdir('insert your changed working directory here')

print(os.getcwd())

FileNotFoundError: [WinError 2] The system cannot find the file specified: 'insert your changed working directory here'

**List of directories and files?**

This method takes in a path and returns a list of subdirectories and files in that path. 
If no path is specified, it returns the list of subdirectories and files from the current working directory.

**Making new directories?** 

This method takes in the path of the new directory. Similar as above, if the full path is not specified, the new directory is created in the current working directory.

In [117]:
#List of directories
os.listdir()

['covid_19_funding_3012021_Mechtenberg_clean_2_revised_GP_LM.rtf',
 'covid_19_funding_3012021_Mechtenberg_clean_v3_Huyen_2401.rtf',
 'covid_19_funding_3012021_Mechtenberg_Huyen_edit_1301.rtf',
 'covid_19_funding_elan_11012020.rtf',
 'covid_19_funding_elan_Huyen_edit.rtf',
 'covid_19_funding_elan_Lydia_v2.rtf',
 'covid_19_funding_elan_Lydia_v3_Huyen_edit.rtf',
 'covid_vaccine_mockup_HN_22022021.pptx',
 'Declaration_of_Compliance_8.4_Huyen_edit.docx',
 'DFG_Forschungsgruppe_KI_Ethik_2020_Nov_6-1.docx',
 'Email_STINE_student_06042021.txt',
 'German_emails.docx',
 'Information_Provision_Experiments-9-1.pdf',
 'Informed and Voluntary Consent.docx',
 'LVformular_SoSe2021 Methodenkurs.pdf',
 'LVformular_SoSe2021 Methodenkurs_HuyenNguyen.pdf',
 'Lydia_meetings.docx',
 'MockUp_AIinCourts_2021-01-20.pptx',
 'MockUp_AIinCourts_2021-02-16-Com_AW.pptx',
 'MockUp_AIinCourts_2021-02-16-Com_AW_HN.pptx',
 'MockUp_AIinCourts_2021-03-11-AW_LM_HN.pptx',
 'MockUp_AIinCourts_2021-03-17_HH_LM_AW_HN.pptx',
 '

In [118]:
# Making new directories? 
os.mkdir('test_folder')

# File handling

## Opening a file

Python has a built-in open() function to open a file. This function returns a file object, also called a handle, as it is used to read or modify the file accordingly.

We can specify the mode while opening a file. 

In mode, we specify whether we want to read r, write w or append a to the file. We can also specify if we want to open the file in text mode or binary mode.

The default is reading in text mode. In this mode, we get strings when reading from the file.

On the other hand, binary mode returns bytes and this is the mode to be used when dealing with non-text files like images or executable files.


In [125]:
#IF YOU ALREADY HAVE A FILE: Locate the path to the file you want to work 
#REMEMBER: use forelash /, NOT backlash \
path_to_file = "insert the path to your file here .....\abcd.xlsx"



In [121]:
#And then open the file
import pandas as pd 
df= pd.read_excel(path_to_file) #If the file has multiple sheet, you can add (path, sheet_name = "Sheet1")
print (df) # view the file

     speech_file_name  speech_id  debate_id  \
0        E08FFzz_S2_M          0          0   
1        E08FFzz_S3_M          1          0   
2        E08FFzz_S4_M          2          0   
3        E08FFzz_S5_M          3          0   
4        E08FFzz_S6_M          4          0   
5        E08FFzz_S7_M          5          0   
6        E08FFzz_S8_M          6          0   
7        E09FFzz_S1_F          7          1   
8        E09FFzz_S2_M          8          1   
9        E09FFzz_S3_M          9          1   
10       E09FFzz_S4_M         10          1   
11       E09FFzz_S5_M         11          1   
12       E09FFzz_S6_M         12          1   
13       E09FFzz_S7_M         13          1   
14       E09FFzz_S8_M         14          1   
15       E09SFzz_S1_M         15          2   
16       E09SFzz_S2_M         16          2   
17       E09SFzz_S3_F         17          2   
18       E09SFzz_S4_M         18          2   
19       E09SFzz_S6_M         19          2   
20       E09S

Check this blog for further information https://datatofish.com/read_excel/

In [ ]:
#IF not, after you have located your preferred working directory, open the chosen file with
 
f = open("test.txt")    # open file in current directory
f = open("C:/Python38/README.txt")  # specifying full path
f = open("test.txt")      # equivalent to 'r' or 'rt'
f = open("test.txt",'w')  # write in text mode
f = open("img.bmp",'r+b') # read and write in binary mode



Check further operations and practise on your own in this tutorial https://www.programiz.com/python-programming/file-operation

**IMPORTANT NOTE on encoding:**

Unlike other languages, the character a does not imply the number 97 until it is encoded using ASCII (or other equivalent encodings).

Moreover, the default encoding is platform dependent. In Windows, it is cp1252 but utf-8 in Linux.

So, we must not rely on the default encoding or else our code will behave differently in different platforms.

Hence, when working with files in text mode, it is highly recommended to *specify the encoding type*.

In [ ]:
f = open("test.txt", encoding = 'utf-8')
# perform file operations
f.close()

## Closing a file 

The safest way to close a file is by using the with statement. This ensures that the file is closed when the block inside the with statement is exited.

We don't need to explicitly call the close() method. It is done internally.

In [ ]:
with open("test.txt", encoding = 'utf-8') as f:
   # perform file operations

# Conditional Statement  
Execute a piece of code only if a set of one or more conditions is satisfied.

(!) Python relies on indentation (whitespace at the beginning of a line) to define scope in the code. Other programming languages often use curly-brackets for this purpose. Try the following example...


In [130]:
x = 5
y = 4
if x>y:
    print("x is larger than y")

x is larger than y


In [134]:
x= 10
y = -1
if x>y:
    print("x is larger than y")
elif x<=y:
    print ("x is smaller than y")

x is larger than y


In [135]:
x= 10
y = 10
if x>y:
    print("x is larger than y")
elif x<y:
    print ("x is smaller than y")
elif x==y:  #MUST be ==, not =
    print ("x equals to y")

x equals to y


### IF, ELSE, FOR statements ALWAYS end with a colon (:)

● Add indentation after an if, else or for statement
if some_condition:
 Next_statement
 
● Maintain indent to indicate the scope of the if/else/for block i.e lines which are 
executed under the condition represented by if/else/for statements.

● Reduce indent back to the level of if/else/for statement to indicate the end of 
that conditional block i.e end of scope of if/else/for statement

● Blank lines and comments are ignored - do not affect indentations or scop

In [142]:
#Nested decision: Which statement will it print? Why?
x = 9
if x>0:
    print("Positive number")
if x>=10:
    print ("More than 1 digit")
    print ("Finished")

Positive number


In [146]:
#Multiway decision: Using if and else only 
#Try different value in the "input" below: -10, 18, 20, 79, 4, 2, 11
input = -10
x = int(input)  # Python int() function? 
if x<=5:
    print ('small')
else:
    if x<=10:
        print ('small')
    else:
        print ('high')

small


In [147]:
#What about elif?
input = 2
x = int(input)
if x<=5:
    print ('small')
elif x<=10:
    print ('small')
else:
    print ('high')

small


### YOUR EXERCISE: 

Categorize shirt sizes given their length, such that:

anything below 30 is size S, between 30 and 35 is M, between 35 and 40 is L, between 40 and 50 is XL, otherwise XXL.

In [151]:
#Example: elif for shirt size length categorization
input = 37
x = int(input)
if x<=30:
    print  ('S')
elif x<=35:
    print ('M')
elif x<=40:
    print ('L')
elif x<=50:
    print ('XL')
else:
    print ('XXL')

L


=> **elif** helps avoid too many nested statements and improves readability.

**Example**: Search whether university X belongs to the lists below with if/elif/else conditions.

In [94]:
excellent_uni = ["RWTH Aachen", "Berlin U Alliance", "Bonn", "TU Dresden", "Uni Hamburg", "Uni Heidelberg", "KIT", 
"Uni Konstanz", "LMU", "TUM", "Uni Tuebingen"] 
ivys = ['Harvard','Yale','Princeton','Columbia','Dartmouth','Brown','Cornell','Penn']

In [152]:
uni = "Harvard"
if uni in excellent_uni:
    print("Excellent Initiative University") 
elif uni in ivys:
    print("Ivy League University")
else:
    print("Neither Excellent Intiative nor Ivy League University")

Ivy League University


# Functions

Python functions are defined using the `def` keyword. For example:

In [154]:
def sign(x):
    if x > 0:
        return 'positive'
    elif x < 0:
        return 'negative'
    else:
        return 'zero'

for x in [-1, 20, 0]:
    print(sign(x))



negative
positive
zero


We will often define functions to take optional keyword arguments, like this:

In [207]:
def hello(name, big=False):
    if big:
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hi, {}!'.format(name))

hello('Bob')
hello('Wendy', big=True)

Hi, Bob!
HELLO, WENDY


# Classes

Python is an object oriented programming language. Almost everything in Python is an object, with its properties and methods.
A Class is like an object constructor, or a "blueprint" for creating objects. 

Class definitions, like function definitions (def statements) must be executed before they have any effect. Here is the detailed documentation of classes in Python.https://docs.python.org/3/tutorial/classes.html

The syntax for defining classes in Python is straightforward:

In [208]:
class Greeter:

    # Constructor
    def __init__(self, name):
        self.name = name  # Create an instance variable

    # Instance method
    def greet(self, big=False):
        if big:
          print('HELLO, {}'.format(self.name.upper()))
        else:
          print('Hello, {}!'.format(self.name))

g = Greeter('Henry')  # Construct an instance of the Greeter class
g.greet()            # Call an instance method; prints "Hello, Fred"
g.greet(big=True)   # Call an instance method; prints "HELLO, FRED!"

Hello, Henry!
HELLO, HENRY


All classes have a function called __init__(), which is always executed when the class is being initiated. The __init__() function is called automatically every time the class is being used to create a new object.


Use the __init__() function to assign values to object properties, or other operations that are necessary to do when the object is being created. Take an example below:

In [165]:
class Person:
  def __init__(self, name, age):
    self.name = name
    self.age = age

p1 = Person("John", 36)

print(p1.name)
print(p1.age)

John
36


# Loops (for)

Begins with for keyword, always with pre-determined exit condition.



In [166]:
n = [5, 4, 3, 2, 1]
for i in n:
 print(i)
print("L(i)ft off!!")
      

5
4
3
2
1
L(i)ft off!!


One useful command: None = denotes nothing in the Python world.

(You can use value is None, OR value == None, both are fine).


In [ ]:
if value is None:
 print ("Does not exist")
else:
 print(value)

**YOUR EXERCISE:** Print...

(1) all numbers that are greater than 20

(2) sum of numbers 

(3) average 

(4) smallest/largest number 

of the list below.

In [ ]:
#This is the number list you can play around with for the exercise
number_list = [0, 15, 23, 28, 50, -5, 3, 20]


Loops can also be used with strings. In fact, in Python, you can iterate over any type ‘iterable’ of data / object sets.


for char in string:

for string in string_list:

for key in dictionary:

for number in number_list:

for any_object in objects_list:

for line in file().text.read()

In [168]:
names = ['Hermione', 'Harry', 'Ron'] #List of names, works with strings too
for name in names:
 print(name)

Hermione
Harry
Ron


# Numpy

Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays. If you are already familiar with MATLAB, you might find this [tutorial](http://wiki.scipy.org/NumPy_for_Matlab_Users) useful to get started with Numpy.

To start with numpy, we need to import the package, as follows:

In [170]:
import numpy as np

## Array

A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

We can initialize numpy arrays from nested Python lists, and access elements using square brackets:

In [172]:
a = np.array([1, 2, 3])  # Create a rank 1 array
print(type(a), a.shape, a[0], a[1], a[2])
a[0] = 10                # Change an element of the array
print(a)    

<class 'numpy.ndarray'> (3,) 1 2 3
[10  2  3]


In [174]:
b = np.array([[1,2,3],[4,5,6]])   # Create a rank 2 array
print(b)

[[1 2 3]
 [4 5 6]]


In [175]:
print(b.shape)
print(b[0, 0], b[0, 1], b[1, 0]) # [x,y] = [row,column] (0 = first, 1 = second...)

(2, 3)
1 2 4


Numpy also provides many functions to create arrays:

In [178]:
a = np.zeros((3,5))  # Create an array of all zeros
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [181]:
b = np.ones((3,6))   # Create an array of all ones
print(b)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [183]:
c = np.full((2,2), 10) # Create a constant array
print(c)

[[10 10]
 [10 10]]


In [185]:
d = np.eye(6)        # Create a 2x2 identity matrix
print(d)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [187]:
e = np.random.random((9,6)) # Create an array filled with random values
print(e)

[[0.75439813 0.15539091 0.33836008 0.15705843 0.61726493 0.24367625]
 [0.58247485 0.41069497 0.8440117  0.17935535 0.59595308 0.48658702]
 [0.79728245 0.0416252  0.52247357 0.39623523 0.11282335 0.38107101]
 [0.70245189 0.78346541 0.71463105 0.06676463 0.18329011 0.76700365]
 [0.9038227  0.15247867 0.54455628 0.85579134 0.12374589 0.3452705 ]
 [0.02519027 0.78402939 0.00239982 0.28707814 0.95376468 0.25104218]
 [0.93893126 0.64107431 0.94833694 0.58530271 0.1843876  0.91802416]
 [0.41090426 0.98465772 0.09811888 0.28488722 0.31417824 0.11715241]
 [0.87498631 0.67327945 0.96063951 0.04170101 0.39014574 0.448285  ]]


### Array Indexing

**Slicing**: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array:


In [190]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:3, 1:3] #row 0 and 1, elements columns of (n-1)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  3]
 [ 6  7]
 [10 11]]


A slice of an array is a view into the same data, so modifying it will modify the original array.

In [194]:
print(a[0, 1]) 
b[0, 0] = 77    # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1]) 

77
77


You can also mix integer indexing with slice indexing. However, doing so will yield an array of lower rank than the original array. 

**NOTE!** This is quite different from the way that MATLAB handles array slicing:

In [195]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Two ways of accessing the data in the middle row of the array.
Mixing integer indexing with slices yields an array of lower rank,
while using only slices yields an array of the same rank as the
original array:

In [199]:
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
row_r3 = a[[1], :]  # Rank 2 view of the second row of a
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [196]:
row_r1 = a[1, :]    # Rank 1 view of the second row of a  
print(row_r1, row_r1.shape)


[5 6 7 8] (4,)


In [197]:
# We can make the same distinction when accessing columns of an array:

col_r2 = a[:, 1:2]
print()
print(col_r2, col_r2.shape)

[ 2  6 10] (3,)

[[ 2]
 [ 6]
 [10]] (3, 1)


In [198]:
col_r1 = a[:, 1] 
print(col_r1, col_r1.shape)


[ 2  6 10] (3,)


**Integer array indexing**

When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array. Here is an example:

In [209]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [201]:
# An example of integer array indexing.
# The returned array will have shape (3,) and 
print(a[[0, 1, 2], [0, 1, 0]]) 

[1 4 5]


In [210]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]


In [211]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])

# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


*One* useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [212]:
# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [213]:
# Create an array of indices
b = np.array([0, 2, 0, 1])

# Select one element from each row of a using the indices in b
print(a[np.arange(4), b])  # Prints "[ 1  6  7 11]"

[ 1  6  7 11]


In [214]:
# Mutate one element from each row of a using the indices in b
a[np.arange(4), b] += 10
print(a)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


**Boolean array indexing** 

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:

In [202]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # Find the elements of a that are bigger than 2;
                    # this returns a numpy array of Booleans of the same
                    # shape as a, where each slot of bool_idx tells
                    # whether that element of a is > 2.

print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [203]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])

# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


**Data types with numpy**

Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. 

Here is an example:

In [206]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.5, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


You can read all about numpy datatypes in the [documentation](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html).

### Array Math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [ ]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)



In [ ]:
# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))

In [ ]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

In [ ]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

In [ ]:
# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

In [ ]:
# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

**NOTE**: Unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication. We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices. dot is available both as a function in the numpy module and as an instance method of array objects:

In [109]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


You can also use the `@` operator which is equivalent to numpy's `dot` 
*   List item
*   List item

operator.

In [110]:
print(v @ w)

219


In [ ]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

In [ ]:
# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))
print(x @ y)

Numpy provides many useful functions for performing computations on arrays; one of the most useful is `sum`:

In [ ]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

You can find the full list of mathematical functions provided by numpy in the [documentation](http://docs.scipy.org/doc/numpy/reference/routines.math.html).

Apart from computing mathematical functions using arrays, we frequently need to reshape or otherwise manipulate data in arrays. The simplest example of this type of operation is transposing a matrix; to transpose a matrix, simply use the T attribute of an array object:

In [ ]:
print(x)
print("transpose\n", x.T)

In [ ]:
v = np.array([[1,2,3]])
print(v )
print("transpose\n", v.T)

### Broadcasting

Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array.

For example, suppose that we want to add a constant vector to each row of a matrix. We could do it like this:

In [ ]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

This works; however when the matrix `x` is very large, computing an explicit loop in Python could be slow. Note that adding the vector v to each row of the matrix `x` is equivalent to forming a matrix `vv` by stacking multiple copies of `v` vertically, then performing elementwise summation of `x` and `vv`. We could implement this approach like this:

In [ ]:
vv = np.tile(v, (4, 1))  # Stack 4 copies of v on top of each other
print(vv)                # Prints "[[1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]
                         #          [1 0 1]]"

In [ ]:
y = x + vv  # Add x and vv elementwise
print(y)

Numpy broadcasting allows us to perform this computation without actually creating multiple copies of v. Consider this version, using broadcasting:

In [ ]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

In [ ]:
The line `y = x + v` works even though `x` has shape `(4, 3)` and `v` has shape `(3,)` due to broadcasting; this line works as if v actually had shape `(4, 3)`, where each row was a copy of `v`, and the sum was performed elementwise.

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

If this explanation does not make sense, try reading the explanation from the [documentation](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) or this [explanation](http://wiki.scipy.org/EricsBroadcastingDoc).

Functions that support broadcasting are known as universal functions. You can find the list of all universal functions in the [documentation](http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs).

Here are some applications of broadcasting:

In [ ]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:

print(np.reshape(v, (3, 1)) * w)

In [ ]:
# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:

print(x + v)

In [ ]:
# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:

print((x.T + w).T)

In [ ]:
# Another solution is to reshape w to be a row vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

In [ ]:
# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
print(x * 2)

Broadcasting typically makes your code more concise and faster, so you should strive to use it where possible.

This brief overview has touched on many of the important things that you 

1.   List item
2.   List item

need to know about numpy, but is far from complete. Check out the [numpy reference](http://docs.scipy.org/doc/numpy/reference/) to find out much more about numpy.